"""Stable language and voice catalogs exposed to the desktop UI."""

POPULAR_TARGET_LANGUAGES = [
    ("vi", "Vietnamese", "Tiếng Việt"),
    ("en", "English", "English"),
    ("zh", "Chinese", "中文"),
    ("hi", "Hindi", "हिन्दी"),
    ("es", "Spanish", "Español"),
    ("fr", "French", "Français"),
    ("ar", "Arabic", "العربية"),
    ("pt", "Portuguese", "Português"),
    ("ru", "Russian", "Русский"),
    ("id", "Indonesian", "Bahasa Indonesia"),
    ("de", "German", "Deutsch"),
    ("ja", "Japanese", "日本語"),
    ("ko", "Korean", "한국어"),
    ("it", "Italian", "Italiano"),
    ("th", "Thai", "ไทย"),
    ("fil", "Filipino", "Filipino"),
]


EDGE_TTS_VOICES_BY_LANGUAGE = {
    "vi": [("vi-VN-HoaiMyNeural", "Hoai My - Female"), ("vi-VN-NamMinhNeural", "Nam Minh - Male")],
    "en": [("en-US-JennyNeural", "Jenny - Female"), ("en-US-GuyNeural", "Guy - Male")],
    "zh": [("zh-CN-XiaoxiaoNeural", "Xiaoxiao - Female"), ("zh-CN-YunxiNeural", "Yunxi - Male")],
    "hi": [("hi-IN-SwaraNeural", "Swara - Female"), ("hi-IN-MadhurNeural", "Madhur - Male")],
    "es": [("es-ES-ElviraNeural", "Elvira - Female"), ("es-ES-AlvaroNeural", "Alvaro - Male")],
    "fr": [("fr-FR-DeniseNeural", "Denise - Female"), ("fr-FR-HenriNeural", "Henri - Male")],
    "ar": [("ar-SA-ZariyahNeural", "Zariyah - Female"), ("ar-SA-HamedNeural", "Hamed - Male")],
    "bn": [("bn-BD-NabanitaNeural", "Nabanita - Female"), ("bn-BD-PradeepNeural", "Pradeep - Male")],
    "pt": [("pt-BR-FranciscaNeural", "Francisca - Female"), ("pt-BR-AntonioNeural", "Antonio - Male")],
    "ru": [("ru-RU-SvetlanaNeural", "Svetlana - Female"), ("ru-RU-DmitryNeural", "Dmitry - Male")],
    "ur": [("ur-PK-UzmaNeural", "Uzma - Female"), ("ur-PK-AsadNeural", "Asad - Male")],
    "id": [("id-ID-GadisNeural", "Gadis - Female"), ("id-ID-ArdiNeural", "Ardi - Male")],
    "de": [("de-DE-KatjaNeural", "Katja - Female"), ("de-DE-ConradNeural", "Conrad - Male")],
    "ja": [("ja-JP-NanamiNeural", "Nanami - Female"), ("ja-JP-KeitaNeural", "Keita - Male")],
    "sw": [("sw-KE-ZuriNeural", "Zuri - Female"), ("sw-KE-RafikiNeural", "Rafiki - Male")],
    "mr": [("mr-IN-AarohiNeural", "Aarohi - Female"), ("mr-IN-ManoharNeural", "Manohar - Male")],
    "te": [("te-IN-ShrutiNeural", "Shruti - Female"), ("te-IN-MohanNeural", "Mohan - Male")],
    "tr": [("tr-TR-EmelNeural", "Emel - Female"), ("tr-TR-AhmetNeural", "Ahmet - Male")],
    "ta": [("ta-IN-PallaviNeural", "Pallavi - Female"), ("ta-IN-ValluvarNeural", "Valluvar - Male")],
    "ko": [("ko-KR-SunHiNeural", "SunHi - Female"), ("ko-KR-InJoonNeural", "InJoon - Male")],
    "it": [("it-IT-ElsaNeural", "Elsa - Female"), ("it-IT-DiegoNeural", "Diego - Male")],
    "th": [("th-TH-PremwadeeNeural", "Premwadee - Female"), ("th-TH-NiwatNeural", "Niwat - Male")],
    "gu": [("gu-IN-DhwaniNeural", "Dhwani - Female"), ("gu-IN-NiranjanNeural", "Niranjan - Male")],
    "pl": [("pl-PL-ZofiaNeural", "Zofia - Female"), ("pl-PL-MarekNeural", "Marek - Male")],
    "uk": [("uk-UA-PolinaNeural", "Polina - Female"), ("uk-UA-OstapNeural", "Ostap - Male")],
    "fa": [("fa-IR-DilaraNeural", "Dilara - Female"), ("fa-IR-FaridNeural", "Farid - Male")],
    "ms": [("ms-MY-YasminNeural", "Yasmin - Female"), ("ms-MY-OsmanNeural", "Osman - Male")],
    "nl": [("nl-NL-FennaNeural", "Fenna - Female"), ("nl-NL-MaartenNeural", "Maarten - Male")],
    "ro": [("ro-RO-AlinaNeural", "Alina - Female"), ("ro-RO-EmilNeural", "Emil - Male")],
    "el": [("el-GR-AthinaNeural", "Athina - Female"), ("el-GR-NestorasNeural", "Nestoras - Male")],
    "cs": [("cs-CZ-VlastaNeural", "Vlasta - Female"), ("cs-CZ-AntoninNeural", "Antonin - Male")],
    "hu": [("hu-HU-NoemiNeural", "Noemi - Female"), ("hu-HU-TamasNeural", "Tamas - Male")],
    "sv": [("sv-SE-SofieNeural", "Sofie - Female"), ("sv-SE-MattiasNeural", "Mattias - Male")],
    "he": [("he-IL-HilaNeural", "Hila - Female"), ("he-IL-AvriNeural", "Avri - Male")],
    "fil": [("fil-PH-BlessicaNeural", "Blessica - Female"), ("fil-PH-AngeloNeural", "Angelo - Male")],
    "my": [("my-MM-NilarNeural", "Nilar - Female"), ("my-MM-ThihaNeural", "Thiha - Male")],
    "km": [("km-KH-SreymomNeural", "Sreymom - Female"), ("km-KH-PisethNeural", "Piseth - Male")],
    "lo": [("lo-LA-KeomanyNeural", "Keomany - Female"), ("lo-LA-ChanthavongNeural", "Chanthavong - Male")],
}
